Bookmarks Feature Implemented Using Local Storage
Sparsh1212/gsocanalyzer pull request #45
Opened 2021-12-04 06:15 UTC by Komachian

Fixes #36 
- [x] Add and delete bookmark option has been added to each organization's card
- [x] A bookmarks page has been created at ```path='/bookmarks'```
- [x] The bookmarks are stored in local storage 

A [video snippet](https://user-images.githubusercontent.com/75087669/144699802-22ceb0af-b066-4bc5-bff9-f9c4c405e984.mp4) has been attached for reference
https://user-images.githubusercontent.com/75087669/144699802-22ceb0af-b066-4bc5-bff9-f9c4c405e984.mp4

2021-12-04 10:14 UTC, Sparsh1212 commented
@Komachian I must say commendable job. This is beyond amazing.
Since, this is quite a big PR so please allow me some time to review it properly and with some minor iterations, this will be ready to be merged 🚀🚀🚀

2021-12-06 17:43 UTC, Sparsh1212 commented on src/components/Footer.js
> +             <button className="clear-storage-btn" onClick={() => {localStorage.clear(); window.location.reload()}}>Clear Local Storage</button>
Please rename "Clear Local Storage" to "Reset Bookmarks"

2021-12-06 17:47 UTC, Sparsh1212 commented on src/css/mainpagecss.css
> +}
Reduce border-radius to `5px` and increase the font-weight.

2021-12-06 17:47 UTC, Sparsh1212 commented on src/css/mainpagecss.css
> +}
Reduce border-radius to `5px` and increase the font-weight.

2021-12-06 17:49 UTC, Sparsh1212 commented on src/css/mainpagecss.css
> +}
Ditto for Home, Bookmarks button.

2021-12-06 17:49 UTC, Sparsh1212 commented on src/components/OrganisationCard.js
> +  async function unBook() {
Rename this to `unBookmark`

2021-12-06 17:59 UTC, Sparsh1212 requested changes
Overall looks like a really good start!
Here are some high-level changes that must be taken care of:

- The path for `Home` should be `/` not `gsocanalyzer`. Also, every path other than `/bookmarks` must lead to `Home`. Lets say if I do `/usgugdu` then it should render the `Home` component.
- For the svgs, please create a new folder in `src` named `assets` and keep these files there. It is a good practice to separate out related files into a relevant folder together.
- It will be better to properly align the "Bookmarks" button inline with the Header. The same applies to the clear local storage button. It shall be aligned with the footer. Currently, their alignment looks a bit odd. In case you can suggest some better position for these buttons then please do.
- Both the buttons are not mobile responsive. When viewed in mobile view, the UI is looking odd. Please make them mobile responsive.

2021-12-06 18:00 UTC, Sparsh1212 commented
@Komachian Please take a look at the comments and also remove the merge conflicts.

2021-12-07 06:09 UTC, Komachian commented
- [x] Path directing behaviour modified as requested
- [x] Icon svgs have been moved to `src/assets`
- [x] Function `unBook()` gotten rid of 
- [x] Navigation and 'Reset Bookmarks' buttons made responsive
- [x] 'Clear Storage' button renamed to 'Reset Bookmarks'
- [x] Buttons aesthetically modified as requested 
- [x] Merge Conflicts Resolved

2021-12-07 06:18 UTC, Komachian commented
A video snippet has been attached below
https://user-images.githubusercontent.com/75087669/144976707-083dd872-3ad3-461a-8a67-ad6c1e1a48df.mp4

2021-12-07 06:24 UTC, Sparsh1212 requested changes
@Komachian Awesome work on the requested changes!
Just one last comment!
I can see there are 18 commits in this PR. Please make sure that it is in proper sync with master, as there are some unnecessary changes in this PR from previous commits. Let me know once it's done.

2021-12-07 06:37 UTC, Komachian commented
The changes certainly do look in sync. The 18 commits are all the commits that were made when I first made the pull request plus every commit added by me/anyone else in the parent directory from then till now (they are listed). It seems that's because GitHub, for some reason doesn't keep track of changes to the target repository.

2021-12-07 06:48 UTC, Sparsh1212 approved these changes
LGTM!
Amazing work .

2021-12-07 06:48 UTC, merged