Clicking header renders launch page
Sparsh1212/gsocanalyzer pull request #47
Opened 2021-12-04 14:33 UTC by chandrashekar27

Made the changes specified in the issue. Now clicking the header (GSoC Analyser) rerenders the launch page. #37

2021-12-04 15:31 UTC, Sparsh1212 requested changes
A good start, but I have a few concerns. The current changes do not clear the input properly. 
What seems a better approach to me is to create an initialState object in the `AdvancedSearch` component. Create a `resetSearchState` function in the `AdvancedSearch` component which sets all the states to the initial state object. That will ensure that all the values are being reset properly. Also note that you will have to invoke the function from the parent component, i.e the `Home` component. There are pretty good answers on StackOverflow regarding invoking a child component function from a parent. Please refer to that if needed.

This shall be the body of `reRenderLauncher`:
```
const reRenderLauncher = () => {
    resetSearchState();
    setValidList([]);
    setDisplayLauncher(true);
}
```

2021-12-04 15:38 UTC, Sparsh1212 commented
> A good start, but I have a few concerns. The current changes do not clear the input properly. What seems a better approach to me is to create an initialState object in the `AdvancedSearch` component. Create a `resetSearchState` function in the `AdvancedSearch` component which sets all the states to the initial state object. That will ensure that all the values are being reset properly. Also note that you will have to invoke the function from the parent component, i.e the `Home` component. There are pretty good answers on StackOverflow regarding invoking a child component function from a parent. Please refer to that if needed.
> 
> This shall be the body of `reRenderLauncher`:
> 
> ```
> const reRenderLauncher = () => {
>     resetSearchState();
>     setValidList([]);
>     setDisplayLauncher(true);
> }
> ```

2021-12-04 15:48 UTC, chandrashekar27 commented
@Sparsh1212 
Alright, will work on it.

2021-12-05 10:56 UTC, chandrashekar27 commented
Hey @Sparsh1212 ! 
I made the changes you requested and it works!! Please take a look.

Also, I had a little trouble with merging the changes made by others(into your `master` branch) into my `issue#37` branch.
It would be great if you could explain the correct method to do that.

2021-12-06 18:10 UTC, Sparsh1212 requested changes
Looks really nice to me.
Just one suggestion:
Please make only the Header text clickable. Not the entire Header space. Currently, if I even click outside the header text, it is getting re-rendered.

2021-12-06 18:11 UTC, Sparsh1212 commented on src/components/AdvancedSearch.js
> +      console.log("YAYYYY!!!!!!");
A nice success indicator,
But we need to remove it :)

2021-12-06 18:13 UTC, Sparsh1212 commented
> Hey @Sparsh1212 ! I made the changes you requested and it works!! Please take a look.
> 
> Also, I had a little trouble with merging the changes made by others(into your `master` branch) into my `issue#37` branch. It would be great if you could explain the correct method to do that.

Ahh, I see. This is because you are facing merge conflicts. I'd suggest reading or watching some tutorials on resolving merge conflicts. Let me know if you are not able to find a relevant resource.

2021-12-07 02:47 UTC, chandrashekar27 commented on src/components/AdvancedSearch.js
> +      console.log("YAYYYY!!!!!!");
Ohh... I thought I had deleted that!

2021-12-07 02:47 UTC, chandrashekar27 commented
Ok, will make the changes.

2021-12-07 04:30 UTC, chandrashekar27 commented
Have made changes. Please review @Sparsh1212

2021-12-07 05:48 UTC, Sparsh1212 commented
LGTM!

2021-12-07 05:48 UTC, Sparsh1212 approved these changes
Nice work :)

2021-12-07 05:48 UTC, merged