Added GSoC stats in home page
Sparsh1212/gsocanalyzer pull request #64
Opened 2021-12-11 17:57 UTC by aritroCoder

Added graphs for different GSOC stats and also a side pane which contains different data related to all previous year GSOC

2021-12-12 07:18 UTC, Sparsh1212 commented
Can you also attach the Demo video

2021-12-12 07:40 UTC, aritroCoder commented
https://user-images.githubusercontent.com/92646038/145704450-77a447ac-2184-471a-aece-5702d9e2868b.mp4

2021-12-12 07:57 UTC, Sparsh1212 requested changes
Some high-level comments:
- The info appearing on the right looks like a repetition of the graphs on the left. It will be best to remove the textual info as all of that could be interpreted from the graphs.
- Since, this is the launcher page, it's fine to render the overall stats of GSoC. By that I mean to say, there's no need for a "Show Summary" button. Please remove that.
- Since we want to make the search distraction-free, so please remove the show summary button from the search too. It will be best to remove it completely from the code.
- Regarding the UI. Finally, I think, it will be best to only render the graphs. That being said, make sure you center the new graphs added. In the first row, center the twp graphs and increase their size (height and width) so that they take the max-width. In the second row, just center the organization's graph, and the size should be around 60-70% of the width.
- The UI is not mobile responsive. In the mobile view, it will be best if each graph can take the full width and we can render the in the form of columns.

2021-12-12 07:59 UTC, aritroCoder commented
> Some high-level comments:
> 
> * The info appearing on the right looks like a repetition of the graphs on the left. It will be best to remove the textual info as all of that could be interpreted from the graphs.
> * Since, this is the launcher page, it's fine to render the overall stats of GSoC. By that I mean to say, there's no need for a "Show Summary" button. Please remove that.
> * Since we want to make the search distraction-free, so please remove the show summary button from the search too. It will be best to remove it completely from the code.
> * Regarding the UI. Finally, I think, it will be best to only render the graphs. That being said, make sure you center the new graphs added. In the first row, center the twp graphs and increase their size (height and width) so that they take the max-width. In the second row, just center the organization's graph, and the size should be around 60-70% of the width.
> * The UI is not mobile responsive. In the mobile view, it will be best if each graph can take the full width and we can render the in the form of columns.

Ok , thanks for your detailed review. I am working on your points

2021-12-12 17:53 UTC, aritroCoder commented
I have made the required changes. Please check the video. If everything looks fine I will commit the code and re initiate the PR.

https://user-images.githubusercontent.com/92646038/145723638-11410f45-2c36-4ac5-9a8c-db3e65da97de.mp4

2021-12-12 19:44 UTC, Sparsh1212 commented
> I have made the required changes. Please check the video. If everything looks fine I will commit the code and re initiate the PR.
> 
>  2021-12-12.23-21-03.mp4

Good job on the suggestions.
After seeing the demo video, I realized that if we individually display the graphs in 100% width even on the desktop view, they look awesome. So final UI changes will be:
- Make each graph almost 90% width and increase the height a bit. So in total there will be a total of 3 rows in both Desktop and Mobile View.
- Increase the spacing between the rows of graphs.
- I was thinking to remove all the launcher data content and keep it a two liner. That being said, remove all the existing content present which starts from "A blazingly fast tool to .... bookmark your favourite organization" and replace it with these two lines: 
1. "A blazingly-fast tool to analyze all the organizations selected in Google Summer of Code."
2. "Start analyzing now!"

2021-12-13 10:17 UTC, Sparsh1212 commented
@aritroCoder Any updates on this?

2021-12-13 11:35 UTC, aritroCoder commented
> > I have made the required changes. Please check the video. If everything looks fine I will commit the code and re initiate the PR.
> > 2021-12-12.23-21-03.mp4
> 
> Good job on the suggestions. After seeing the demo video, I realized that if we individually display the graphs in 100% width even on the desktop view, they look awesome. So final UI changes will be:
> 
> * Make each graph almost 90% width and increase the height a bit. So in total there will be a total of 3 rows in both Desktop and Mobile View.
> * Increase the spacing between the rows of graphs.
> * I was thinking to remove all the launcher data content and keep it a two liner. That being said, remove all the existing content present which starts from "A blazingly fast tool to .... bookmark your favourite organization" and replace it with these two lines:
> 
> 1. "A blazingly-fast tool to analyze all the organizations selected in Google Summer of Code."
> 2. "Start analyzing now!"

Yes I am working on it, it will be ready by tommorow. Thank you!

2021-12-13 17:05 UTC, aritroCoder commented
https://user-images.githubusercontent.com/92646038/145856287-4aa59c21-123e-469c-9f79-3bd651d9496e.mp4

I have made the requested changes, please see them and give any feedback

2021-12-13 17:19 UTC, Sparsh1212 commented
> 2021-12-13.22-33-56.mp4 
> I have made the requested changes, please see them and give any feedback

The UI looks excellent. 
I though observed one small problem with the graph caption text on the mobile screen. Observe the graph caption at the bottom of the graph, please decrease its font size for mobile view. Rest the UI looks perfect to me. Push your code after this suggested fix and then we'll have a final round of code review and then get set go!

2021-12-13 18:18 UTC, aritroCoder commented
> > 2021-12-13.22-33-56.mp4
> > I have made the requested changes, please see them and give any feedback
> 
> The UI looks excellent. I though observed one small problem with the graph caption text on the mobile screen. Observe the graph caption at the bottom of the graph, please decrease its font size for mobile view. Rest the UI looks perfect to me. Push your code after this suggested fix and then we'll have a final round of code review and then get set go!

I came at a different kind of solution for this. React chartjs does not use any CSS, as it renders the chart as a image. So I have used a logic at the code where it will decide the chart font size at the time of loading the screen . As the users wont be changing their screen size, so I think it will not be a issue. Do give your feedback

https://user-images.githubusercontent.com/92646038/145866500-d264c654-17c8-4b53-8d71-ddbf640618d3.mp4

2021-12-13 18:32 UTC, Sparsh1212 commented
> > > 2021-12-13.22-33-56.mp4
> > > I have made the requested changes, please see them and give any feedback
> > 
> > 
> > The UI looks excellent. I though observed one small problem with the graph caption text on the mobile screen. Observe the graph caption at the bottom of the graph, please decrease its font size for mobile view. Rest the UI looks perfect to me. Push your code after this suggested fix and then we'll have a final round of code review and then get set go!
> 
> I came at a different kind of solution for this. React chartjs does not use any CSS, as it renders the chart as a image. So I have used a logic at the code where it will decide the chart font size at the time of loading the screen . As the users wont be changing their screen size, so I think it will not be a issue. Do give your feedback
> 
>  2021-12-13.23-46-18.mp4

The approach sounds so cool to me. 
Also, always don't hesitate to push your code whenever you make a change to your PR. Viewing the change code also helps the reviewer to guess whether the solution has been implemented in the correct way or not. Otherwise, it will lead to unnecessary extra iterations.  :)

2021-12-14 03:11 UTC, aritroCoder commented
I have committed the changes to the PR

2021-12-14 13:35 UTC, aritroCoder commented
Did you check the code? Please check and update your status. Thank you

2021-12-14 19:20 UTC, Sparsh1212 requested changes
- Please remove the commented code
- Make all the three graphs, part of the `LaunchingComponent` . This is because they are a part of the launching screen only, also upon changing the state `display launcher`, you would not have to programmatically make its display to be none. They will automatically be gone from the screen as the LaunchingComponent gets disappeared.

2021-12-14 19:20 UTC, Sparsh1212 commented on src/components/CompanyChart.js
> +                            // ],
Remove.

2021-12-14 19:21 UTC, Sparsh1212 commented on src/components/CompanyChart.js
> +                            // ],
Remove.

2021-12-14 19:21 UTC, Sparsh1212 commented on src/components/CompanyChart.js
> +                // width="300px"
Remove.

2021-12-14 19:21 UTC, Sparsh1212 commented on src/components/GraphChart.js
> +                            // ],
Remove.

2021-12-14 19:21 UTC, Sparsh1212 commented on src/components/GraphChart.js
> +                            // ],
Remove.

2021-12-14 19:21 UTC, Sparsh1212 commented on src/components/GraphChart.js
> +                // width="300px"
Remove.

2021-12-14 19:22 UTC, Sparsh1212 commented on src/components/Home.js
> +  });
Revert the formatting change. Ditto for overall PR. We don't want the formatting to be changed.

2021-12-14 19:22 UTC, Sparsh1212 commented on src/components/Home.js
> +
Remove.

2021-12-14 19:26 UTC, Sparsh1212 commented
Also, please rename the Chart file names with more descriptive names. Replace `Company` with `Organization` everywhere in the naming. Also, if it's easy for you then please try to group all the three graph files into a separate folder under `components` named as `launcher`. And there put all the files of `LaunchingComponent`. This ensures good modularity of the code.

2021-12-15 06:46 UTC, aritroCoder commented
I have done all your requested changes. Please go through the code now and give your suggestions

2021-12-15 06:54 UTC, Sparsh1212 commented on src/components/Home.js
> +
Revert this change

2021-12-15 06:54 UTC, Sparsh1212 commented on src/components/Home.js
> +  });
Revert the formatting change.

2021-12-15 06:54 UTC, Sparsh1212 commented on src/components/Home.js
> +
Remove blank line.

2021-12-15 06:55 UTC, Sparsh1212 commented on src/components/Home.js
> +
Remove blank line.

2021-12-15 06:55 UTC, Sparsh1212 commented on src/components/Home.js
> +
Revert this change.

2021-12-15 06:55 UTC, Sparsh1212 commented on src/components/Home.js
> +
Remove these blank lines.

2021-12-15 06:56 UTC, Sparsh1212 requested changes
Almost LGTM!
Just some nit suggestions added. PTAL.

2021-12-15 06:57 UTC, Sparsh1212 commented
Also, please take care of the merge conflict.

2021-12-15 07:40 UTC, aritroCoder commented
Done :)

2021-12-15 07:45 UTC, Sparsh1212 commented on src/components/Home.js
> +   });
I think this got missed :)

2021-12-15 07:45 UTC, Sparsh1212 commented on src/components/Home.js
> -
Revert

2021-12-15 07:45 UTC, Sparsh1212 commented on src/components/LaunchingComponent.js
> +//Importing the charts files
We don't need this comment

2021-12-15 07:46 UTC, Sparsh1212 commented on src/components/LaunchingComponent.js
> +          <p>Start Analyzing now!</p>
Replace this with: `Start Analyzing now! (Use a comma to separate multiple tags in tech/topic)`

2021-12-15 07:46 UTC, Sparsh1212 commented on src/css/mainpagecss.css
> +} */
Redundant code.

2021-12-15 07:47 UTC, Sparsh1212 requested changes
Some more nits :)
Also can you please add a final video proof after making all these changes?

2021-12-15 12:10 UTC, aritroCoder commented
If this commit is perfect, I will create the final video

2021-12-15 12:31 UTC, Sparsh1212 commented
> If this commit is perfect, I will create the final video

Yeah! things look pretty good to me in the latest commit. Just upload a final video and if everything looks good, then we can go for a merge :)

2021-12-15 14:17 UTC, aritroCoder commented
https://user-images.githubusercontent.com/92646038/146202634-f89a1a0c-424b-40ff-81c1-ad482445ec4f.mp4

https://user-images.githubusercontent.com/92646038/146202736-d32c9ec9-d364-4bf7-a588-1eeb15f58cb7.mp4

second video is for mobile view. 
I think the gap between the typewriter text and chart is too much if you want I can reduce that too

2021-12-15 14:22 UTC, Sparsh1212 commented
> 2021-12-15.19-44-23.mp4 
>  2021-12-15.19-45-00.mp4 
> second video is for mobile view. I think the gap between the typewriter text and chart is too much if you want I can reduce that too

Yes, that will be really good if you could reduce the gap. You can achieve that simply by decreasing the `min-height` of the animatedDiv I think. Also, it will be good if you can slightly increase the separation between the graphs. Don't increase it too much, just a bit.

2021-12-15 14:23 UTC, Sparsh1212 commented
I think after these two fixes, we are fully set to go for a merge.

2021-12-15 14:24 UTC, Sparsh1212 commented
> > 2021-12-15.19-44-23.mp4
> > 2021-12-15.19-45-00.mp4
> > second video is for mobile view. I think the gap between the typewriter text and chart is too much if you want I can reduce that too
> 
> Yes, that will be really good if you could reduce the gap. You can achieve that simply by decreasing the `min-height` of the animatedDiv I think. Make sure to decrease it for the mobile view as well. Also, it will be good if you can slightly increase the separation between the graphs. Don't increase it too much, just a bit.

2021-12-15 14:37 UTC, aritroCoder commented
https://user-images.githubusercontent.com/92646038/146206131-0b483f5f-6b10-4081-81d9-ef034adad889.mp4

https://user-images.githubusercontent.com/92646038/146206193-c3e00041-ae86-405b-bd0d-acd321716c4a.mp4

Done !

2021-12-15 14:49 UTC, Sparsh1212 commented
Just one last change.
You don't need to reupload the video again after this.
Make the min-height in the PC view to be 34vh instead of 54vh. That's it.

2021-12-15 14:53 UTC, aritroCoder commented
Alright, I did that :)

2021-12-15 14:54 UTC, Sparsh1212 approved these changes
LGTM!
Must say, commendable job :)

2021-12-15 14:54 UTC, merged