Sorting Functionality Implemented
Sparsh1212/gsocanalyzer pull request #71
Opened 2021-12-21 17:00 UTC by Komachian

Fixes #70 

Sorting functionality implemented for the following parameters:
- Number of GSoC Appearances
- Total Number of Projects
- Average Number of Projects per Year

Additionally, the ability to specify the order of sorting (ascending, descending) and descriptive labels for dropdowns have been added

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Screenshot
![image](https://user-images.githubusercontent.com/75087669/146969107-da7c9b10-1781-4079-a6b5-5e0988e05ef5.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] The app runs properly
- [x] I have performed a self-review of my own code
- [ ] I have formatted and commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-12-22 04:38 UTC, Sparsh1212 commented
A very good start.
I have some suggestions for the UI though:
1. Make sure the "Search By" is just aligned exactly vertical to "Tech stack". Make sure that they are equally aligned. The same applies to "Sort By" and "Total Number of Projects"
2. Just shift down the sort drop down a bit more downwards.
3. Make sure the UI also works fine for mobile view.

2021-12-22 04:38 UTC, Sparsh1212 requested changes
PTAL at the comments added.

2021-12-23 07:24 UTC, Komachian commented
Responsiveness has been introduced as seen in the video snippet attached below
https://user-images.githubusercontent.com/75087669/147204035-edbccf54-e7bd-4893-a107-3d39bf6b64c4.mp4

2021-12-26 05:05 UTC, Sparsh1212 requested changes
Please increase the separation between the (filters&sort) and the search box. Make it twice the current separation.
Also, just to confirm is the average been calculated as total no. of projects / total number of times in GSoC to total no. of projects / Total GSoC Years (that will always be 13). Please let me know because the former is correct and the latter is incorrect.

2021-12-28 01:49 UTC, Komachian commented
@Sparsh1212 
- The vertical separation between the search box and those drop-downs right?

Also, just to confirm is the average been calculated as:
total no. of projects / total number of times in GSoC or is it:
total no. of projects / Total GSoC Years (that will always be 13).
Please let me know because the former is correct and the latter is incorrect.

- It's the former alright

2021-12-28 04:48 UTC, Sparsh1212 commented
> 

Yes I meant the vertical separation.

2021-12-28 13:46 UTC, Komachian commented
Increased vertical separation 
![image](https://user-images.githubusercontent.com/75087669/147572617-4d471df1-608b-464f-8eda-30826ba84072.png)

2021-12-29 14:01 UTC, Sparsh1212 commented on src/components/SortFunctions.js
> +export function sort0(a, b) {
Can you please give more intuitive names to these functions? names like xyz1 xyz2 lead to confusion when we scale the application. Currently, there are few functions, but in the future, there can be many and it's hard to recognize them from numerical naming.

2021-12-29 14:02 UTC, Sparsh1212 commented on src/components/SortFunctions.js
> +export function sort0(a, b) {
Ditto for all other functions.

2021-12-29 14:03 UTC, Sparsh1212 requested changes
Mostly everything looks good to me. Just left a single comment and once you address it, I'll do a final testing and will merge it if everything goes well :)

2022-01-01 08:06 UTC, Sparsh1212 approved these changes
LGTM!
Very nice work :)

2022-01-01 08:06 UTC, merged